# Generated by Django 3.0.2 on 2020-01-07 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=20)),
                ('bio', models.CharField(max_length=500)),
                ('username', models.CharField(max_length=20)),
                ('img', models.ImageField(upload_to='pics')),
                ('countrycode', models.CharField(max_length=5)),
                ('phone', models.IntegerField(max_length=15)),
                ('address', models.CharField(max_length=500)),
                ('pincode', models.IntegerField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
    ]
